### ISSUE TITLE
TypeError when trying to use position in a ufw firewall_rule

### ISSUE THREAD

**Issue by stottsan** [opscode-cookbooks/firewall#49]
When trying to use position in a ufw firewall_rule, Chef is failing with a **TypeError: no implicit conversion from nil to integer**.  Full details of the run are below, but I was able to work around this by forcing the position attribute to a string in the apply_rule function on line 69 of provider_firewall_rule_ufw.rb as follows:

```
ufw_command << 'insert' << new_resource.position.to_s if new_resource.position
```

With this change in place, the Chef run succeeds and the rules (all of them) are applied correctly.  

Has anyone else seen this?  Thanks!

```
==> web: ==========================================================================
==> web: Error executing action `reject` on resource 'firewall_rule[block-1.1.1.1]'
==> web: ==========================================================================
==> web: 
==> web: 
==> web: TypeError
==> web: ---------
==> web: no implicit conversion from nil to integer
==> web: 
==> web: 
==> web: Cookbook Trace:
==> web: ---------------
==> web: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/firewall/libraries/provider_firewall_rule_ufw.rb:78:in `block (2 levels) in apply_rule'
==> web: 
==> web: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/poise/libraries/subcontext_block.rb:82:in `instance_eval'
==> web: 
==> web: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/poise/libraries/subcontext_block.rb:82:in `subcontext_block'
==> web: 
==> web: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/poise/libraries/notifying_block.rb:33:in `notifying_block'
==> web: 
==> web: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/firewall/libraries/provider_firewall_rule_ufw.rb:76:in `block in apply_rule'
==> web: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/firewall/libraries/provider_firewall_rule_ufw.rb:75:in `apply_rule'
==> web: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/firewall/libraries/provider_firewall_rule_ufw.rb:46:in `action_reject'
==> web: 
==> web: Resource Declaration:
==> web: ---------------------
==> web: # In /tmp/vagrant-chef-2/chef-solo-1/cookbooks/mycookbook/recipes/firewall.rb
==> web: 
==> web:   9:   firewall_rule "block-#{bad_ip}" do
==> web:  10:     source bad_ip
==> web:  11:     position 1
==> web:  12:     action :reject
==> web:  13:   end
==> web:  14: end
==> web: 
==> web: Compiled Resource:
==> web: ------------------
==> web: # Declared in /tmp/vagrant-chef-2/chef-solo-1/cookbooks/mycookbook/recipes/firewall.rb:9:in `block in from_file'
==> web: 
==> web: firewall_rule("block-1.1.1.1") do
==> web:   action [:reject]
==> web:   retries 0
==> web:   retry_delay 2
==> web:   default_guard_interpreter :default
==> web:   declared_type :firewall_rule
==> web:   cookbook_name :"mycookbook"
==> web:   recipe_name "firewall"
==> web:   parent firewall[ufw]
==> web:   source "1.1.1.1"
==> web:   position 1
==> web:   protocol :tcp
==> web:   direction :in
==> web: end
==> web: 
==> web: [2015-03-28T16:13:27+00:00] INFO: Running queued delayed notifications before re-raising exception
==> web: [2015-03-28T16:13:27+00:00] ERROR: Running exception handlers
==> web: [2015-03-28T16:13:27+00:00] ERROR: Exception handlers complete
==> web: [2015-03-28T16:13:27+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> web: [2015-03-28T16:13:27+00:00] ERROR: firewall_rule[block-1.1.1.1] (mycookbook::firewall line 9) had an error: TypeError: no implicit conversion from nil to integer
==> web: [2015-03-28T16:13:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by stottsan** [comment]
FYI, this also happens when trying a firewall_rule with position in Test Kitchen:

```
       Recipe: firewall-test::default
         * firewall[default] action enable[2015-03-28T17:03:11+00:00] WARN: Cloning resource attributes for apt_package[ufw] from prior resource (CHEF-3694)
       [2015-03-28T17:03:11+00:00] WARN: Previous apt_package[ufw]: /tmp/kitchen/cookbooks/firewall/libraries/provider_firewall_ufw.rb:27:in `block in action_enable'
       [2015-03-28T17:03:11+00:00] WARN: Current  apt_package[ufw]: /tmp/kitchen/cookbooks/firewall/libraries/provider_firewall_ufw.rb:27:in `block in action_enable'
       
           * apt_package[ufw] action install (up to date)
       [2015-03-28T17:03:11+00:00] WARN: Cloning resource attributes for template[/etc/default/ufw] from prior resource (CHEF-3694)
       [2015-03-28T17:03:11+00:00] WARN: Previous template[/etc/default/ufw]: /tmp/kitchen/cookbooks/firewall/libraries/provider_firewall_ufw.rb:31:in `block in action_enable'
       [2015-03-28T17:03:11+00:00] WARN: Current  template[/etc/default/ufw]: /tmp/kitchen/cookbooks/firewall/libraries/provider_firewall_ufw.rb:31:in `block in action_enable'
           * template[/etc/default/ufw] action create (up to date)
           - install ufw, template some defaults, and ufw enable
         * apt_package[ufw] action nothing (skipped due to action :nothing)
         * template[/etc/default/ufw] action nothing (skipped due to action :nothing)
       Recipe: firewall::default
         * firewall_rule[allow world to ssh] action allow (up to date)
       Recipe: <Dynamically Defined Resource>
         * ruby_block[subresource_noop] action nothing (skipped due to action :nothing)
       Recipe: firewall-test::default
         * firewall_rule[established] action allow (skipped due to only_if)
         * firewall_rule[ssh22] action allow (up to date)
         * firewall_rule[ssh2222] action allow
           - firewall_rule[ssh2222] in proto tcp to any port 2222,2200 from any
         * firewall_rule[temp1] action deny
           - firewall_rule[temp1] in proto tcp to any port 1234 from any
         * firewall_rule[temp2] action reject
           - firewall_rule[temp2] in proto tcp to any port 1235 from any
         * firewall_rule[addremove] action allow
           - firewall_rule[addremove] in proto tcp to any port 1236 from any
         * firewall_rule[addremove2] action deny
           - firewall_rule[addremove2] in proto tcp to any port 1236 from any
         * firewall_rule[duplicate0] action allow
           - firewall_rule[duplicate0] in proto tcp to any port 1111 from any
         * firewall_rule[duplicate0] action allow
           - firewall_rule[duplicate0] in proto tcp to any port 5432,5431 from any
         * firewall_rule[duplicate1] action allow (up to date)
         * firewall_rule[duplicate1] action allow
           - firewall_rule[duplicate1] in proto tcp to any port 5432,5431 from any
         * firewall_rule[position] action reject
           
           ================================================================================
           Error executing action `reject` on resource 'firewall_rule[position]'
           ================================================================================
           
           TypeError
           ---------
           no implicit conversion from nil to integer
           
           Cookbook Trace:
           ---------------
       /tmp/kitchen/cookbooks/firewall/libraries/provider_firewall_rule_ufw.rb:76:in `block (2 levels) in apply_rule'
           /tmp/kitchen/cookbooks/poise/libraries/subcontext_block.rb:82:in `instance_eval'
           /tmp/kitchen/cookbooks/poise/libraries/subcontext_block.rb:82:in `subcontext_block'
           /tmp/kitchen/cookbooks/poise/libraries/notifying_block.rb:33:in `notifying_block'
           /tmp/kitchen/cookbooks/firewall/libraries/provider_firewall_rule_ufw.rb:74:in `block in apply_rule'
           /tmp/kitchen/cookbooks/firewall/libraries/provider_firewall_rule_ufw.rb:73:in `apply_rule'
           /tmp/kitchen/cookbooks/firewall/libraries/provider_firewall_rule_ufw.rb:46:in `action_reject'
           
       Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/firewall-test/recipes/default.rb
           
            62: firewall_rule 'position' do
            63:   source '1.1.1.1'
            64:   position 1
            65:   action :reject
            66: end
           
           Compiled Resource:
           ------------------
       # Declared in /tmp/kitchen/cookbooks/firewall-test/recipes/default.rb:62:in `from_file'
           
           firewall_rule("position") do
             action [:reject]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :firewall_rule
             cookbook_name :"firewall-test"
             recipe_name "default"
             source "1.1.1.1"
             parent firewall[default]
             position 1
             protocol :tcp
             direction :in
           end
           
       
       Running handlers:
       
       Running handlers complete
       [2015-03-28T17:03:14+00:00] ERROR: Exception handlers complete
       [2015-03-28T17:03:14+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 19 resources updated in 34.597102663 seconds
       [2015-03-28T17:03:14+00:00] ERROR: firewall_rule[position] (firewall-test::default line 62) had an error: TypeError: no implicit conversion from nil to integer
       [2015-03-28T17:03:14+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-ubuntu-1404>.
```

**Comment by martinb3** [comment]
Released in v1.0.1.

**Comment by martinb3** [comment]
Thank you for the bug report!!

**Comment by stottsan** [comment]
LOL, just made the same code and spec changes in a local branch...  :smile:  Thanks for the quick fix!!!
