### ISSUE TITLE
Intermittent ProviderNotFound Exception

### ISSUE THREAD

**Issue by jslusher** [opscode-cookbooks/firewall#78]
I have the firewall cookbook in my base cookbook repo and a resource that configures the firewall for my centos nodes. I've been getting these at random points, usually when the base cookbook is specified in the run list before the node's recipes. If I reverse the order and have the base last in the order in the run list, I don't get this Exception. I want to be able to specify the base cookbook first in the run list for obvious reasons. What's going on with this?

           ================================================================================
           Error executing action `enable` on resource 'firewall[centos-firewall]'
           ================================================================================

           Chef::Exceptions::ProviderNotFound
           ----------------------------------
           Cannot find a provider for firewall[centos-firewall] on centos version 7.0.1406

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/discogs-base/recipes/default.rb

            91:   firewall 'centos-firewall' do
            92:     action :enable
            93:   end
            94:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/discogs-base/recipes/default.rb:91:in `from_file'

           firewall("centos-firewall") do
             action [:enable]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             subresources [firewall_rule[consul], firewall_rule[consul400], firewall_rule[consul500], firewall_rule[consul600], firewall_rule[nrpe], firewall_rule[ssh], firewall_rule[mysql], firewall_rule[app], firewall_rule[http]]
             declared_type :firewall
             cookbook_name "discogs-base"
             recipe_name "default"
           end

**Comment by martinb3** [comment]
Hi @jslusher - I wonder if it has to do with your platform version `7.0.1406`? I'm not used to seeing a bugfix release in that string. Could you share with us your chef version, contents of `/etc/redhat-release` (where ohai gets version from), and the output of `ohai | grep platform`?

The current mapping statement _seems_ like it would satisfy your version:
```
Chef::Platform.set platform: :centos, version: '>= 7.0', resource: :firewall, provider: Chef::Provider::FirewallFirewalld
```

Here's what I get on our test CentOS 7.0 images for `ohai | grep platform`:
```
# ohai | grep platform
  "platform": "centos",
  "platform_version": "7.0.1406",
  "platform_family": "rhel",
```

**Comment by jslusher** [comment]
ohai | grep platform
      "platform": "centos",
      "platform_version": "7.0.1406",
      "platform_family": "rhel",

    cat /etc/redhat-release
    CentOS Linux release 7.0.1406 (Core)

           Starting Chef Client, version 12.4.1

**Comment by martinb3** [comment]
Hmm. Everything there looks correct. Do you have `depends 'firewall'` in the base cookbook's metadata?

**Comment by jslusher** [comment]
depends 'firewall', '~> 1.6.0'

**Comment by jslusher** [comment]
I just got it to work on Chef version 12.2.1

**Comment by martinb3** [comment]
I'm not sure about intermittent behavior, but I was able to converge on our centos-7.0 test suite with chef chef-12.4.1 just fine.

**Comment by jslusher** [comment]
Yeah, I don't know what to say. It recently started doing this, and like I said, if the base cookbook isn't the first item in the run list of a chef node, it work every time. It's only when the base cookbook is listed as the first in the list. I'll lock the Chef version to 12.2.1 and update this if it ends up happening on that version. Thanks for responding to this. It's a really strange issue.

**Comment by jslusher** [comment]
If your testing were to use a role that called it from a cookbook that had the lwrps in the default recipe, I wonder if it would reproduce the problem. It seems pretty consistent using chef 12.4.1 when in this configuration. 

My role file looks like this:
https://gist.github.com/jslusher/5a38a97ac9d964ce86ad

The firewall section in recipes/default.rb of my base cookbook looks like this:
https://gist.github.com/jslusher/d465875d75830d69774e

**Comment by martinb3** [comment]
@jslusher the CI testing we do is actually very, very similar. The only major difference is not using a role, and calling `include_recipe 'firewall'` from the test fixture (what would be your 'base' recipe in this analogy). Can you see if you can reproduce by no longer adding firewall to the runlist, but including it from base?

Also, it seems like you're enabling the firewall in base, and then running `firewall::default` which enables the firewall again under a different resource name. While the provider is capable of detecting it is already running (and hence, idempotent to some degree), maybe that's some part of the issue?

**Comment by dev-head** [comment]
@martinb3 it looks like i might be seeing the same issue, i'm not sure what i might be missing. This happens on every attempt, I haven't gotten the cookbook to work at all. 

Here are the debugging details:

#### vm
```sh

# chef-client -version
Chef: 12.4.1

# ohai | grep platform
  "platform": "centos",
  "platform_version": "6.6",
  "platform_family": "rhel",


# cat /etc/redhat-release
CentOS release 6.6 (Final)
```

#### workstation
```sh
⇒  grep "firewall" metadata.rb 
depends "firewall"

```

#### My Cookbook


```ruby
include_recipe 'firewall'

```


#### Error

```sh

       Recipe: firewall::default
         * firewall[default] action enable
           
           ================================================================================
           Error executing action `enable` on resource 'firewall[default]'
           ================================================================================
           
           Chef::Exceptions::ProviderNotFound
           ----------------------------------
           Cannot find a provider for firewall[default] on centos version 6.6
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/firewall/recipes/default.rb
           
            20: firewall 'default' do
            21:   action :enable
            22: end
            23: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/firewall/recipes/default.rb:20:in `from_file'
           
           firewall("default") do
             action [:enable]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             subresources [firewall_rule[allow world to ssh]]
             declared_type :firewall
             cookbook_name "firewall"
             recipe_name "default"
           end
           
       
       Running handlers:
       [2015-07-31T19:41:58+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-07-31T19:41:58+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 12.246211079 seconds
       [2015-07-31T19:41:58+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-07-31T19:41:58+00:00] ERROR: firewall[default] (firewall::default line 20) had an error: Chef::Exceptions::ProviderNotFound: Cannot find a provider for firewall[default] on centos version 6.6
       [2015-07-31T19:42:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
rake aborted!

```

#### Stacktrace log:

```sh
Chef::Exceptions::ProviderNotFound: firewall[default] (firewall::default line 20) had an error: Chef::Exceptions::ProviderNotFound: Cannot find a provider for firewall[default] on centos version 6.6
/opt/chef/embedded/apps/chef/lib/chef/platform/provider_mapping.rb:179:in `find_provider'
/opt/chef/embedded/apps/chef/lib/chef/platform/provider_mapping.rb:106:in `find_provider_for_node'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:129:in `maybe_chef_platform_lookup'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:62:in `resolve'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1205:in `provider_for_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:55:in `load'
/opt/chef/bin/chef-client:55:in `<main>'

```

**Comment by martinb3** [comment]
@dev-head @jslusher Could you give the current master a try? I think it should resolve this.

**Comment by thwpike** [comment]
@martinb3 I have just tried the current master on CentOS 7.1.1503 with the same error:

```
  * firewall[default] action install

    ================================================================================
    Error executing action `install` on resource 'firewall[default]'
    ================================================================================

    Chef::Exceptions::ProviderNotFound
    ----------------------------------
    Cannot find a provider for firewall[default] on centos version 7.1.1503

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/firewall/recipes/default.rb

     22: firewall 'default' do
     23:   action :install
     24: end
     25:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/firewall/recipes/default.rb:22:in `from_file'

    firewall("default") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :firewall
      cookbook_name "firewall"
      recipe_name "default"
    end
```

Our platform data is as follows:

```
[root@vm-centos-test-03 ~]# ohai | grep platform
  "platform": "centos",
  "platform_version": "7.1.1503",
  "platform_family": "rhel",
[root@vm-centos-test-03 ~]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
[root@vm-centos-test-03 ~]# chef-client -version
Chef: 12.4.1
```

**Comment by martinb3** [comment]
My best guess here is that the Chef 11 ways for setting providers are slowly being broken in Chef 12. I think I'm going to go ahead and do a major release and bump the required version of Chef to 12.

**Comment by martinb3** [comment]
Hi folks -- I've done the work to make it chef-12 only going forward, and that invokes an entirely new mechanism for choosing providers. Please give that a try if you're on chef 12. Going to release v2.0 with that change. Please ping this issue and I'll reopen if it's still a problem after using the v2.0.0 cookbook version.

**Comment by thwpike** [comment]
@martinb3 this seems to have fixed the issue.  Thanks for your help.

**Comment by rayterrill** [comment]
I'm getting this same issue with chef-client 12.16.42, Server2012R2 machines.

Example below. Should I open a new ticket on this?
```
------------------------------------------------------
                      EXCEPTION                       
------------------------------------------------------
Chef::Exceptions::ProviderNotFound: dsc_resource[NetFramework35Core] (SQLServer::default line 15) had an error: Chef::Exceptions::ProviderNotFound: ["You must have Powershell version >= 5.0.10018.0 to use dsc_resource."]
------------------------------------------------------
                     STACK TRACE                      
------------------------------------------------------
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/why_run.rb:240:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/why_run.rb:321:in `block in run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/why_run.rb:320:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/why_run.rb:320:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider.rb:155:in `process_resource_requirements'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider.rb:133:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:669:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:664:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:664:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:703:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:283:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:65:in `load'
C:/opscode/chef/bin/chef-client:65:in `<main>'
```

**Comment by martinb3** [comment]
Hi @rayterrill -- I'm not sure what your error has to do with this cookbook... since `dsc_resource` is a core resource in Chef, you could probably open an issue on that project: https://github.com/chef/chef/issues/new

**Comment by rayterrill** [comment]
You're right - my bad. Somehow I missed that this wasn't in Chef core - just that it was the same error. :(
